import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "NotoSansJP",
    fontSize: 10,
    paddingTop: 50,
    paddingBottom: 60,
    paddingHorizontal: 50,
    backgroundColor: "#ffffff",
  },
  coverPage: {
    fontFamily: "NotoSansJP",
    fontSize: 10,
    paddingTop: 80,
    paddingBottom: 60,
    paddingHorizontal: 60,
    backgroundColor: "#ffffff",
  },
  coverTitle: {
    fontFamily: "NotoSansJP",
    fontSize: 24,
    fontWeight: 700,
    textAlign: "center",
    marginBottom: 20,
    color: "#1a1a2e",
  },
  coverSubtitle: {
    fontFamily: "NotoSansJP",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 60,
    color: "#444444",
  },
  coverCompanyBlock: {
    marginTop: 40,
    padding: 20,
    borderWidth: 1,
    borderColor: "#cccccc",
    borderRadius: 4,
  },
  coverLabel: {
    fontFamily: "NotoSansJP",
    fontSize: 9,
    color: "#888888",
    marginBottom: 4,
  },
  coverValue: {
    fontFamily: "NotoSansJP",
    fontSize: 11,
    color: "#1a1a1a",
    marginBottom: 12,
  },
  sectionHeader: {
    fontFamily: "NotoSansJP",
    fontSize: 13,
    fontWeight: 700,
    color: "#1a1a2e",
    marginTop: 24,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 2,
    borderBottomColor: "#1a1a2e",
  },
  bodyText: {
    fontFamily: "NotoSansJP",
    fontSize: 10,
    lineHeight: 1.7,
    color: "#333333",
    marginBottom: 6,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    textAlign: "center",
    fontSize: 9,
    fontFamily: "NotoSansJP",
    color: "#aaaaaa",
    borderTopWidth: 1,
    borderTopColor: "#eeeeee",
    paddingTop: 6,
  },
});
